952 bulk upload awards
UKGovernmentBEIS/transparency-db-publishing-subsidies-service pull request #1
Opened 2020-12-23 09:47 UTC by vamsikrishna-api

feat: Bulk upload service APi changes

2020-12-23 10:13 UTC, KOTLAPRA2711 requested changes
Committed many unnecessary files  which are not required and also please cleanup the code as well

2020-12-23 10:13 UTC, KOTLAPRA2711 commented on src/main/java/com/beis/subsidy/award/transperancy/dbpublishingservice/model/Award.java
> +	@SequenceGenerator(name = "award_read_seq",sequenceName="award_read_seq",allocationSize=1)
Auto generator not required . please remove from here.

2020-12-23 10:13 UTC, KOTLAPRA2711 commented on src/main/java/com/beis/subsidy/award/transperancy/dbpublishingservice/model/Beneficiary.java
> +	@SequenceGenerator(name = "beneficiary_read_seq",sequenceName="beneficiary_read_seq",allocationSize=1)
Auto generator not required here since already using sequence generator . please remove from here.

2020-12-23 10:13 UTC, KOTLAPRA2711 commented on src/main/java/com/beis/subsidy/award/transperancy/dbpublishingservice/model/SearchInput.java
> +	private String susidyObjective;
are we using this class? if not please delete

2020-12-23 10:13 UTC, KOTLAPRA2711 commented on src/main/java/com/beis/subsidy/award/transperancy/dbpublishingservice/model/SearchResults.java
> +
same here . are we using this class?

2020-12-23 10:13 UTC, KOTLAPRA2711 commented on src/main/java/com/beis/subsidy/award/transperancy/dbpublishingservice/service/AwardService.java
> +	private static final String CONSTANT_SYSTEM = "SYSTEM";
Create interface  ,declare methods and add implementation class add business logic.

2020-12-23 10:13 UTC, KOTLAPRA2711 commented on src/main/java/com/beis/subsidy/award/transperancy/dbpublishingservice/service/AwardService.java
> +		//log.info(smMap);
remove sysouts here

2020-12-23 10:13 UTC, KOTLAPRA2711 commented on src/main/java/com/beis/subsidy/award/transperancy/dbpublishingservice/util/ExcelHelper.java
> +	          case 9:
remove all sysouts across the files

2021-01-05 08:42 UTC, vamsikrishna-api commented
5-Jan-2021 Azure configuration changes

2021-01-05 08:47 UTC, chhagan19 approved these changes

2021-01-05 08:51 UTC, merged